// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// AllFinite
LogicalVector AllFinite(SEXP pDat);
RcppExport SEXP netrep_AllFinite(SEXP pDatSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type pDat(pDatSEXP );
        LogicalVector __result = AllFinite(pDat);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// DataProps
List DataProps(SEXP pDat, SEXP pScaledDat, IntegerVector subsetIndices);
RcppExport SEXP netrep_DataProps(SEXP pDatSEXP, SEXP pScaledDatSEXP, SEXP subsetIndicesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type pDat(pDatSEXP );
        Rcpp::traits::input_parameter< SEXP >::type pScaledDat(pScaledDatSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type subsetIndices(subsetIndicesSEXP );
        List __result = DataProps(pDat, pScaledDat, subsetIndices);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// GetDiag
NumericVector GetDiag(SEXP pBigMat);
RcppExport SEXP netrep_GetDiag(SEXP pBigMatSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP );
        NumericVector __result = GetDiag(pBigMat);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// SetDiag
void SetDiag(SEXP pBigMat, NumericVector value);
RcppExport SEXP netrep_SetDiag(SEXP pBigMatSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type value(valueSEXP );
        SetDiag(pBigMat, value);
    }
    return R_NilValue;
END_RCPP
}
// NetProps
List NetProps(SEXP pAdjacency, IntegerVector subsetIndices);
RcppExport SEXP netrep_NetProps(SEXP pAdjacencySEXP, SEXP subsetIndicesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type pAdjacency(pAdjacencySEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type subsetIndices(subsetIndicesSEXP );
        List __result = NetProps(pAdjacency, subsetIndices);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// Scale
void Scale(SEXP pDat, SEXP spDat);
RcppExport SEXP netrep_Scale(SEXP pDatSEXP, SEXP spDatSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type pDat(pDatSEXP );
        Rcpp::traits::input_parameter< SEXP >::type spDat(spDatSEXP );
        Scale(pDat, spDat);
    }
    return R_NilValue;
END_RCPP
}
