// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// GetDiag
NumericVector GetDiag(SEXP pBigMat);
RcppExport SEXP netrep_GetDiag(SEXP pBigMatSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP );
        NumericVector __result = GetDiag(pBigMat);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// SetDiag
void SetDiag(SEXP pBigMat, NumericVector value);
RcppExport SEXP netrep_SetDiag(SEXP pBigMatSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type value(valueSEXP );
        SetDiag(pBigMat, value);
    }
    return R_NilValue;
END_RCPP
}
// KIM
NumericVector KIM(SEXP pAdjacency, IntegerVector moduleIndices);
RcppExport SEXP netrep_KIM(SEXP pAdjacencySEXP, SEXP moduleIndicesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type pAdjacency(pAdjacencySEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type moduleIndices(moduleIndicesSEXP );
        NumericVector __result = KIM(pAdjacency, moduleIndices);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// MeanAdj
NumericVector MeanAdj(SEXP pAdjacency, IntegerVector moduleIndices);
RcppExport SEXP netrep_MeanAdj(SEXP pAdjacencySEXP, SEXP moduleIndicesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type pAdjacency(pAdjacencySEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type moduleIndices(moduleIndicesSEXP );
        NumericVector __result = MeanAdj(pAdjacency, moduleIndices);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
