# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' big.matrix diagonals
#' 
#' @param pBigMat a \code{numeric} \code{\link[bigmemory]{big.matrix}}
#' @return a vector containing the diagonal of \code{pBigMat}
GetDiag <- function(pBigMat) {
    .Call('netrep_GetDiag', PACKAGE = 'netrep', pBigMat)
}

#' big.matrix diagonals
#' 
#' @param pBigMat a \code{numeric} \code{\link[bigmemory]{big.matrix}}
#' @param value either a single \code{numeric} value or \code{numeric} vector 
#'   of length equal to the current diagonal.
SetDiag <- function(pBigMat, value) {
    invisible(.Call('netrep_SetDiag', PACKAGE = 'netrep', pBigMat, value))
}

#' C++ implementation of Intramodular Connectivity (Degree).
#' 
#' See the \link[=kIM]{wrapper function} for documentation.
#' 
#' @param pAdjacency SEXP container for the pointer to the adjacency matrix
#' @param subsetIndices indices of the subset of the network to calculate
#'   the mean adjacency for.
#' @return A vector containing the intramodular connectivity (degree) of 
#'   each node. 
#' @rdname kIM-cpp
KIM <- function(pAdjacency, subsetIndices) {
    .Call('netrep_KIM', PACKAGE = 'netrep', pAdjacency, subsetIndices)
}

#' C++ implementation of Mean Adjacency
#' 
#' See the \link[=meanAdj]{wrapper function} for documentation.
#' 
#' @param pAdjacency SEXP container for the pointer to the adjacency matrix
#' @param subsetIndices indices of the subset of the network to calculate
#'   the mean adjacency for.
#' @param undirected logical; If \code{TRUE}, only the lower half of the 
#'   adjacency matrix is used to calculate the \code{meanAdj}, halving the 
#'   calculation time.
#' @return A single numeric value.
#' @rdname meanAdj-cpp
MeanAdj <- function(pAdjacency, subsetIndices, undirected) {
    .Call('netrep_MeanAdj', PACKAGE = 'netrep', pAdjacency, subsetIndices, undirected)
}

#' Scale a matrix by its rows
#' 
#' @param pDat SEXP container for the pointer to the data matrix to be scaled.
#' @param spDat SEXP container for the pointer to the pre-initialised
#'   \code{\link[bigmemory]{big.matrix}} that the scaled version of \code{pDat}
#'   will be stored in.
#' @rdname scale-cpp
Scale <- function(pDat, spDat) {
    invisible(.Call('netrep_Scale', PACKAGE = 'netrep', pDat, spDat))
}

#' Network subset eigenvector and proportion of variance explained in C++
#' 
#' @param pDat SEXP container for the pointer to the data matrix used in 
#'   network construction.
#' @param pScaledDat SEXP container for the pointer to a scaled version of the 
#'   data matrix used to construct the network.
#' @param subsetIndices indices of the network subset of interest in 
#'   \code{pDat}.
#' 
#' @return
#'  A list whose first element is the first eigenvector of the singular value
#'  decomposition for the network subset, and whose second element is the 
#'  proportion of the variance in the corresponding subset of \code{pDat} the 
#'  eigenvector explains.
#'  
#' @details
#'  The sign of the returned eigenvector is modified to match the average of
#'  \code{pDat}. This is to match the behaviour of 
#'  \code{\link[WGCNA]{moduleEigengenes}} in the \code{\link{WGCNA}} package.
#'  
#'  The two returned properties are bundled together into one function because
#'  the calculation of the proportion of variance requires much of the same
#'  underlying intermediate calculations that obtaining the first eigenvector
#'  requires.
#' 
#' @import RcppArmadillo
#' @rdname dataSummary-cpp
#'  
DataSummary <- function(pDat, pScaledDat, subsetIndices) {
    .Call('netrep_DataSummary', PACKAGE = 'netrep', pDat, pScaledDat, subsetIndices)
}

