# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' big.matrix diagonals
#' 
#' @param pBigMat a \code{numeric} \code{\link[bigmemory]{big.matrix}}
#' @return a vector containing the diagonal of \code{pBigMat}
GetDiag <- function(pBigMat) {
    .Call('netrep_GetDiag', PACKAGE = 'netrep', pBigMat)
}

#' big.matrix diagonals
#' 
#' @param pBigMat a \code{numeric} \code{\link[bigmemory]{big.matrix}}
#' @param value either a single \code{numeric} value or \code{numeric} vector 
#'   of length equal to the current diagonal.
SetDiag <- function(pBigMat, value) {
    invisible(.Call('netrep_SetDiag', PACKAGE = 'netrep', pBigMat, value))
}

KIM <- function(pAdjacency, moduleIndices) {
    .Call('netrep_KIM', PACKAGE = 'netrep', pAdjacency, moduleIndices)
}

MeanAdj <- function(pAdjacency, moduleIndices) {
    .Call('netrep_MeanAdj', PACKAGE = 'netrep', pAdjacency, moduleIndices)
}

