# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Mean Adjacency and Intramodular Connectivity
#'
#' @param pAdjacency SEXP container for the pointer to the adjacency matrix.
#' @param subsetIndices indices of the network subset of interest.
#'   
#' @return
#'   A List containing:
#'   \enumerate{
#'     \item{\emph{kIM}:}{The weighted within-subset degree for each node.}
#'     \item{\emph{mean.adj}:}{The mean absolute edge weight of the network subset.}
#'   }
#' @rdname AdjProps-cpp
AdjProps <- function(pAdjacency, subsetIndices) {
    .Call('fastModPres_AdjProps', PACKAGE = 'fastModPres', pAdjacency, subsetIndices)
}

#' Check the elements of a `big.matrix`
#' 
#' Are all the values finite? 
#' 
#' @param pDat SEXP container for the pointer to the 
#'   \code{\link[bigmemory]{big.matrix}} to be checked.
#'
#' @rdname chekcFinite-cpp
CheckFinite <- function(pDat) {
    invisible(.Call('fastModPres_CheckFinite', PACKAGE = 'fastModPres', pDat))
}

#' Calculate the Correlation of Coexpression and Mean Sign-Aware Coexpression
#'
#' Both of the coexpression statistics are calculated using all pairwise 
#' coexpression values in both the \emph{discovery} and \emph{test} datasets
#' respectively. For the other statistics, it makes sense to calculate the 
#' properties for the discovery network in advance to reduce calculation time
#' and memory. For these statistics this strategy doesn't make sense.
#'
#' @param pCoexpD,pCoexpT SEXP containers for the pointers to the coexpression 
#'  matrices for the \emph{discovery} and \emph{test} networks respectively.
#' @param discIndices,testIndices indices of the network subset in
#'   the \emph{discovery} and \emph{test} networks respectively.
#'
#' @return
#'   A vector containing:
#'   \enumerate{
#'     \item{\emph{cor.coexp}:}{
#'       The correlation between the subset coexpression for both networks.
#'     }
#'     \item{\emph{mean.coexp}:}{
#'       The mean correlation density of the network subset.
#'     }
#'   }
#'   
#' @references
#'   \enumerate{
#'     \item{
#'       Langfelder, P., Luo, R., Oldham, M. C. & Horvath, S. \emph{Is my 
#'       network module preserved and reproducible?} PLoS Comput. Biol. 
#'       \strong{7}, e1001057 (2011). 
#'     }
#'  }
#' @rdname CoexpStats-cpp
CoexpStats <- function(pCoexpD, discIndices, pCoexpT, testIndices) {
    .Call('fastModPres_CoexpStats', PACKAGE = 'fastModPres', pCoexpD, discIndices, pCoexpT, testIndices)
}

#' Network subset eigenvector and proportion of variance explained in C++
#' 
#' @param pDat SEXP container for the pointer to a scaled version of the 
#'   data matrix used to construct the network.
#' @param subsetIndices indices of the network subset of interest in 
#'   \code{pDat}.
#' 
#' @return
#'  A list containing:
#'  \enumerate{
#'   \item{\emph{"SEP"}:}{
#'     The Summary Expression Profile of each node (see details).
#'   }
#'   \item{\emph{"MM"}:}{
#'     The Module Membership of each node (see details).
#'   }
#'   \item{\emph{"pve"}:}{
#'     The proportion of the variance explained by the subset's summary 
#'     expression profile (see details).
#'   }
#'  }
#'  
#' @references
#'  \enumerate{
#'     \item{
#'       Langfelder, P., Luo, R., Oldham, M. C. & Horvath, S. \emph{Is my
#'       network module preserved and reproducible?} PLoS Comput. Biol. 
#'       \strong{7}, e1001057 (2011). 
#'     }
#'  }
#'  
#' @details
#'  First, a summar expression profile (SEP) is calculated for the 
#'  module from the underlying gene expression data. This corresponds to the 
#'  first eigenvector of a principal component analysis \emph{(1)}. 
#'  
#'  The orientation of the eigenvector is modified so that its sign is in the
#'  same direction as the gene expression (on average).
#'  
#'  The Module Membership (MM) is thus quantified as the correlation between each
#'  gene in the module and the summary expression profile.
#'  
#'  The proportion of variance in the module's gene expression data explained 
#'  by the summary expression profile (pve) is quantified as the average square
#' of the Module Membership \emph{(1)}.
#' 
#' @import RcppArmadillo
#' @rdname dataProps-cpp
#'  
DataProps <- function(pDat, subsetIndices) {
    .Call('fastModPres_DataProps', PACKAGE = 'fastModPres', pDat, subsetIndices)
}

#' Get the range of a big.matrix
#' 
#' @description
#'  \code{RangeSubset}: get the range of values in the column-subset of a 
#'  big.matrix.
#' 
#' @param pDat SEXP container for the pointer to the data matrix to be scaled.
#' @param subsetIndices indices of the network subset of interest in 
#'   \code{pDat}.
#'   
#' @rdname range-cpp
RangeSubset <- function(pDat, subsetIndices) {
    .Call('fastModPres_RangeSubset', PACKAGE = 'fastModPres', pDat, subsetIndices)
}

#' @name range-cpp
#' @description
#'   \code{BigRange}: get the range of values in a big.matrix
#' 
BigRange <- function(pDat) {
    .Call('fastModPres_BigRange', PACKAGE = 'fastModPres', pDat)
}

#' Scale a matrix by its rows
#' 
#' @param pDat SEXP container for the pointer to the data matrix to be scaled.
#' @param spDat SEXP container for the pointer to the pre-initialised
#'   \code{\link[bigmemory]{big.matrix}} that the scaled version of \code{pDat}
#'   will be stored in.
#' @rdname scale-cpp
Scale <- function(pDat, spDat) {
    invisible(.Call('fastModPres_Scale', PACKAGE = 'fastModPres', pDat, spDat))
}

